// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	Pool           *pool
	PoolSender     *poolSender
	ServerIP       *serverIP
	ServerIPLog    *serverIPLog
	Task           *task
	TaskLog        *taskLog
	TaskLogArchive *taskLogArchive
	TaskPool       *taskPool
	User           *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Pool = &Q.Pool
	PoolSender = &Q.PoolSender
	ServerIP = &Q.ServerIP
	ServerIPLog = &Q.ServerIPLog
	Task = &Q.Task
	TaskLog = &Q.TaskLog
	TaskLogArchive = &Q.TaskLogArchive
	TaskPool = &Q.TaskPool
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		Pool:           newPool(db, opts...),
		PoolSender:     newPoolSender(db, opts...),
		ServerIP:       newServerIP(db, opts...),
		ServerIPLog:    newServerIPLog(db, opts...),
		Task:           newTask(db, opts...),
		TaskLog:        newTaskLog(db, opts...),
		TaskLogArchive: newTaskLogArchive(db, opts...),
		TaskPool:       newTaskPool(db, opts...),
		User:           newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Pool           pool
	PoolSender     poolSender
	ServerIP       serverIP
	ServerIPLog    serverIPLog
	Task           task
	TaskLog        taskLog
	TaskLogArchive taskLogArchive
	TaskPool       taskPool
	User           user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Pool:           q.Pool.clone(db),
		PoolSender:     q.PoolSender.clone(db),
		ServerIP:       q.ServerIP.clone(db),
		ServerIPLog:    q.ServerIPLog.clone(db),
		Task:           q.Task.clone(db),
		TaskLog:        q.TaskLog.clone(db),
		TaskLogArchive: q.TaskLogArchive.clone(db),
		TaskPool:       q.TaskPool.clone(db),
		User:           q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Pool:           q.Pool.replaceDB(db),
		PoolSender:     q.PoolSender.replaceDB(db),
		ServerIP:       q.ServerIP.replaceDB(db),
		ServerIPLog:    q.ServerIPLog.replaceDB(db),
		Task:           q.Task.replaceDB(db),
		TaskLog:        q.TaskLog.replaceDB(db),
		TaskLogArchive: q.TaskLogArchive.replaceDB(db),
		TaskPool:       q.TaskPool.replaceDB(db),
		User:           q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Pool           IPoolDo
	PoolSender     IPoolSenderDo
	ServerIP       IServerIPDo
	ServerIPLog    IServerIPLogDo
	Task           ITaskDo
	TaskLog        ITaskLogDo
	TaskLogArchive ITaskLogArchiveDo
	TaskPool       ITaskPoolDo
	User           IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Pool:           q.Pool.WithContext(ctx),
		PoolSender:     q.PoolSender.WithContext(ctx),
		ServerIP:       q.ServerIP.WithContext(ctx),
		ServerIPLog:    q.ServerIPLog.WithContext(ctx),
		Task:           q.Task.WithContext(ctx),
		TaskLog:        q.TaskLog.WithContext(ctx),
		TaskLogArchive: q.TaskLogArchive.WithContext(ctx),
		TaskPool:       q.TaskPool.WithContext(ctx),
		User:           q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
