// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"turbo-mailer-server/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPool(db *gorm.DB, opts ...gen.DOOption) pool {
	_pool := pool{}

	_pool.poolDo.UseDB(db, opts...)
	_pool.poolDo.UseModel(&models.Pool{})

	tableName := _pool.poolDo.TableName()
	_pool.ALL = field.NewAsterisk(tableName)
	_pool.ID = field.NewUint(tableName, "id")
	_pool.CreatedAt = field.NewTime(tableName, "created_at")
	_pool.UpdatedAt = field.NewTime(tableName, "updated_at")
	_pool.DeletedAt = field.NewField(tableName, "deleted_at")
	_pool.Name = field.NewString(tableName, "name")
	_pool.Description = field.NewString(tableName, "description")
	_pool.SenderCount = field.NewInt(tableName, "sender_count")
	_pool.Senders = poolHasManySenders{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Senders", "models.PoolSender"),
	}

	_pool.fillFieldMap()

	return _pool
}

type pool struct {
	poolDo poolDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Name        field.String
	Description field.String
	SenderCount field.Int
	Senders     poolHasManySenders

	fieldMap map[string]field.Expr
}

func (p pool) Table(newTableName string) *pool {
	p.poolDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pool) As(alias string) *pool {
	p.poolDo.DO = *(p.poolDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pool) updateTableName(table string) *pool {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.Name = field.NewString(table, "name")
	p.Description = field.NewString(table, "description")
	p.SenderCount = field.NewInt(table, "sender_count")

	p.fillFieldMap()

	return p
}

func (p *pool) WithContext(ctx context.Context) IPoolDo { return p.poolDo.WithContext(ctx) }

func (p pool) TableName() string { return p.poolDo.TableName() }

func (p pool) Alias() string { return p.poolDo.Alias() }

func (p pool) Columns(cols ...field.Expr) gen.Columns { return p.poolDo.Columns(cols...) }

func (p *pool) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pool) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["name"] = p.Name
	p.fieldMap["description"] = p.Description
	p.fieldMap["sender_count"] = p.SenderCount

}

func (p pool) clone(db *gorm.DB) pool {
	p.poolDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pool) replaceDB(db *gorm.DB) pool {
	p.poolDo.ReplaceDB(db)
	return p
}

type poolHasManySenders struct {
	db *gorm.DB

	field.RelationField
}

func (a poolHasManySenders) Where(conds ...field.Expr) *poolHasManySenders {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a poolHasManySenders) WithContext(ctx context.Context) *poolHasManySenders {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a poolHasManySenders) Session(session *gorm.Session) *poolHasManySenders {
	a.db = a.db.Session(session)
	return &a
}

func (a poolHasManySenders) Model(m *models.Pool) *poolHasManySendersTx {
	return &poolHasManySendersTx{a.db.Model(m).Association(a.Name())}
}

type poolHasManySendersTx struct{ tx *gorm.Association }

func (a poolHasManySendersTx) Find() (result []*models.PoolSender, err error) {
	return result, a.tx.Find(&result)
}

func (a poolHasManySendersTx) Append(values ...*models.PoolSender) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a poolHasManySendersTx) Replace(values ...*models.PoolSender) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a poolHasManySendersTx) Delete(values ...*models.PoolSender) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a poolHasManySendersTx) Clear() error {
	return a.tx.Clear()
}

func (a poolHasManySendersTx) Count() int64 {
	return a.tx.Count()
}

type poolDo struct{ gen.DO }

type IPoolDo interface {
	gen.SubQuery
	Debug() IPoolDo
	WithContext(ctx context.Context) IPoolDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPoolDo
	WriteDB() IPoolDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPoolDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPoolDo
	Not(conds ...gen.Condition) IPoolDo
	Or(conds ...gen.Condition) IPoolDo
	Select(conds ...field.Expr) IPoolDo
	Where(conds ...gen.Condition) IPoolDo
	Order(conds ...field.Expr) IPoolDo
	Distinct(cols ...field.Expr) IPoolDo
	Omit(cols ...field.Expr) IPoolDo
	Join(table schema.Tabler, on ...field.Expr) IPoolDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPoolDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPoolDo
	Group(cols ...field.Expr) IPoolDo
	Having(conds ...gen.Condition) IPoolDo
	Limit(limit int) IPoolDo
	Offset(offset int) IPoolDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPoolDo
	Unscoped() IPoolDo
	Create(values ...*models.Pool) error
	CreateInBatches(values []*models.Pool, batchSize int) error
	Save(values ...*models.Pool) error
	First() (*models.Pool, error)
	Take() (*models.Pool, error)
	Last() (*models.Pool, error)
	Find() ([]*models.Pool, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Pool, err error)
	FindInBatches(result *[]*models.Pool, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Pool) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPoolDo
	Assign(attrs ...field.AssignExpr) IPoolDo
	Joins(fields ...field.RelationField) IPoolDo
	Preload(fields ...field.RelationField) IPoolDo
	FirstOrInit() (*models.Pool, error)
	FirstOrCreate() (*models.Pool, error)
	FindByPage(offset int, limit int) (result []*models.Pool, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPoolDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p poolDo) Debug() IPoolDo {
	return p.withDO(p.DO.Debug())
}

func (p poolDo) WithContext(ctx context.Context) IPoolDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p poolDo) ReadDB() IPoolDo {
	return p.Clauses(dbresolver.Read)
}

func (p poolDo) WriteDB() IPoolDo {
	return p.Clauses(dbresolver.Write)
}

func (p poolDo) Session(config *gorm.Session) IPoolDo {
	return p.withDO(p.DO.Session(config))
}

func (p poolDo) Clauses(conds ...clause.Expression) IPoolDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p poolDo) Returning(value interface{}, columns ...string) IPoolDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p poolDo) Not(conds ...gen.Condition) IPoolDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p poolDo) Or(conds ...gen.Condition) IPoolDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p poolDo) Select(conds ...field.Expr) IPoolDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p poolDo) Where(conds ...gen.Condition) IPoolDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p poolDo) Order(conds ...field.Expr) IPoolDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p poolDo) Distinct(cols ...field.Expr) IPoolDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p poolDo) Omit(cols ...field.Expr) IPoolDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p poolDo) Join(table schema.Tabler, on ...field.Expr) IPoolDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p poolDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPoolDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p poolDo) RightJoin(table schema.Tabler, on ...field.Expr) IPoolDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p poolDo) Group(cols ...field.Expr) IPoolDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p poolDo) Having(conds ...gen.Condition) IPoolDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p poolDo) Limit(limit int) IPoolDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p poolDo) Offset(offset int) IPoolDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p poolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPoolDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p poolDo) Unscoped() IPoolDo {
	return p.withDO(p.DO.Unscoped())
}

func (p poolDo) Create(values ...*models.Pool) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p poolDo) CreateInBatches(values []*models.Pool, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p poolDo) Save(values ...*models.Pool) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p poolDo) First() (*models.Pool, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Pool), nil
	}
}

func (p poolDo) Take() (*models.Pool, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Pool), nil
	}
}

func (p poolDo) Last() (*models.Pool, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Pool), nil
	}
}

func (p poolDo) Find() ([]*models.Pool, error) {
	result, err := p.DO.Find()
	return result.([]*models.Pool), err
}

func (p poolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Pool, err error) {
	buf := make([]*models.Pool, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p poolDo) FindInBatches(result *[]*models.Pool, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p poolDo) Attrs(attrs ...field.AssignExpr) IPoolDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p poolDo) Assign(attrs ...field.AssignExpr) IPoolDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p poolDo) Joins(fields ...field.RelationField) IPoolDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p poolDo) Preload(fields ...field.RelationField) IPoolDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p poolDo) FirstOrInit() (*models.Pool, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Pool), nil
	}
}

func (p poolDo) FirstOrCreate() (*models.Pool, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Pool), nil
	}
}

func (p poolDo) FindByPage(offset int, limit int) (result []*models.Pool, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p poolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p poolDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p poolDo) Delete(models ...*models.Pool) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *poolDo) withDO(do gen.Dao) *poolDo {
	p.DO = *do.(*gen.DO)
	return p
}
