// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"turbo-mailer-server/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPoolSender(db *gorm.DB, opts ...gen.DOOption) poolSender {
	_poolSender := poolSender{}

	_poolSender.poolSenderDo.UseDB(db, opts...)
	_poolSender.poolSenderDo.UseModel(&models.PoolSender{})

	tableName := _poolSender.poolSenderDo.TableName()
	_poolSender.ALL = field.NewAsterisk(tableName)
	_poolSender.ID = field.NewUint(tableName, "id")
	_poolSender.CreatedAt = field.NewTime(tableName, "created_at")
	_poolSender.UpdatedAt = field.NewTime(tableName, "updated_at")
	_poolSender.DeletedAt = field.NewField(tableName, "deleted_at")
	_poolSender.PoolID = field.NewUint(tableName, "pool_id")
	_poolSender.FromName = field.NewString(tableName, "from_name")
	_poolSender.FromEmail = field.NewString(tableName, "from_email")
	_poolSender.ReplyTo = field.NewString(tableName, "reply_to")
	_poolSender.Domain = field.NewString(tableName, "domain")

	_poolSender.fillFieldMap()

	return _poolSender
}

type poolSender struct {
	poolSenderDo poolSenderDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	PoolID    field.Uint
	FromName  field.String
	FromEmail field.String
	ReplyTo   field.String
	Domain    field.String

	fieldMap map[string]field.Expr
}

func (p poolSender) Table(newTableName string) *poolSender {
	p.poolSenderDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p poolSender) As(alias string) *poolSender {
	p.poolSenderDo.DO = *(p.poolSenderDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *poolSender) updateTableName(table string) *poolSender {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.PoolID = field.NewUint(table, "pool_id")
	p.FromName = field.NewString(table, "from_name")
	p.FromEmail = field.NewString(table, "from_email")
	p.ReplyTo = field.NewString(table, "reply_to")
	p.Domain = field.NewString(table, "domain")

	p.fillFieldMap()

	return p
}

func (p *poolSender) WithContext(ctx context.Context) IPoolSenderDo {
	return p.poolSenderDo.WithContext(ctx)
}

func (p poolSender) TableName() string { return p.poolSenderDo.TableName() }

func (p poolSender) Alias() string { return p.poolSenderDo.Alias() }

func (p poolSender) Columns(cols ...field.Expr) gen.Columns { return p.poolSenderDo.Columns(cols...) }

func (p *poolSender) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *poolSender) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["pool_id"] = p.PoolID
	p.fieldMap["from_name"] = p.FromName
	p.fieldMap["from_email"] = p.FromEmail
	p.fieldMap["reply_to"] = p.ReplyTo
	p.fieldMap["domain"] = p.Domain
}

func (p poolSender) clone(db *gorm.DB) poolSender {
	p.poolSenderDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p poolSender) replaceDB(db *gorm.DB) poolSender {
	p.poolSenderDo.ReplaceDB(db)
	return p
}

type poolSenderDo struct{ gen.DO }

type IPoolSenderDo interface {
	gen.SubQuery
	Debug() IPoolSenderDo
	WithContext(ctx context.Context) IPoolSenderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPoolSenderDo
	WriteDB() IPoolSenderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPoolSenderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPoolSenderDo
	Not(conds ...gen.Condition) IPoolSenderDo
	Or(conds ...gen.Condition) IPoolSenderDo
	Select(conds ...field.Expr) IPoolSenderDo
	Where(conds ...gen.Condition) IPoolSenderDo
	Order(conds ...field.Expr) IPoolSenderDo
	Distinct(cols ...field.Expr) IPoolSenderDo
	Omit(cols ...field.Expr) IPoolSenderDo
	Join(table schema.Tabler, on ...field.Expr) IPoolSenderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPoolSenderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPoolSenderDo
	Group(cols ...field.Expr) IPoolSenderDo
	Having(conds ...gen.Condition) IPoolSenderDo
	Limit(limit int) IPoolSenderDo
	Offset(offset int) IPoolSenderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPoolSenderDo
	Unscoped() IPoolSenderDo
	Create(values ...*models.PoolSender) error
	CreateInBatches(values []*models.PoolSender, batchSize int) error
	Save(values ...*models.PoolSender) error
	First() (*models.PoolSender, error)
	Take() (*models.PoolSender, error)
	Last() (*models.PoolSender, error)
	Find() ([]*models.PoolSender, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PoolSender, err error)
	FindInBatches(result *[]*models.PoolSender, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.PoolSender) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPoolSenderDo
	Assign(attrs ...field.AssignExpr) IPoolSenderDo
	Joins(fields ...field.RelationField) IPoolSenderDo
	Preload(fields ...field.RelationField) IPoolSenderDo
	FirstOrInit() (*models.PoolSender, error)
	FirstOrCreate() (*models.PoolSender, error)
	FindByPage(offset int, limit int) (result []*models.PoolSender, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPoolSenderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p poolSenderDo) Debug() IPoolSenderDo {
	return p.withDO(p.DO.Debug())
}

func (p poolSenderDo) WithContext(ctx context.Context) IPoolSenderDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p poolSenderDo) ReadDB() IPoolSenderDo {
	return p.Clauses(dbresolver.Read)
}

func (p poolSenderDo) WriteDB() IPoolSenderDo {
	return p.Clauses(dbresolver.Write)
}

func (p poolSenderDo) Session(config *gorm.Session) IPoolSenderDo {
	return p.withDO(p.DO.Session(config))
}

func (p poolSenderDo) Clauses(conds ...clause.Expression) IPoolSenderDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p poolSenderDo) Returning(value interface{}, columns ...string) IPoolSenderDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p poolSenderDo) Not(conds ...gen.Condition) IPoolSenderDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p poolSenderDo) Or(conds ...gen.Condition) IPoolSenderDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p poolSenderDo) Select(conds ...field.Expr) IPoolSenderDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p poolSenderDo) Where(conds ...gen.Condition) IPoolSenderDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p poolSenderDo) Order(conds ...field.Expr) IPoolSenderDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p poolSenderDo) Distinct(cols ...field.Expr) IPoolSenderDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p poolSenderDo) Omit(cols ...field.Expr) IPoolSenderDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p poolSenderDo) Join(table schema.Tabler, on ...field.Expr) IPoolSenderDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p poolSenderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPoolSenderDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p poolSenderDo) RightJoin(table schema.Tabler, on ...field.Expr) IPoolSenderDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p poolSenderDo) Group(cols ...field.Expr) IPoolSenderDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p poolSenderDo) Having(conds ...gen.Condition) IPoolSenderDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p poolSenderDo) Limit(limit int) IPoolSenderDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p poolSenderDo) Offset(offset int) IPoolSenderDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p poolSenderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPoolSenderDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p poolSenderDo) Unscoped() IPoolSenderDo {
	return p.withDO(p.DO.Unscoped())
}

func (p poolSenderDo) Create(values ...*models.PoolSender) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p poolSenderDo) CreateInBatches(values []*models.PoolSender, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p poolSenderDo) Save(values ...*models.PoolSender) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p poolSenderDo) First() (*models.PoolSender, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.PoolSender), nil
	}
}

func (p poolSenderDo) Take() (*models.PoolSender, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.PoolSender), nil
	}
}

func (p poolSenderDo) Last() (*models.PoolSender, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.PoolSender), nil
	}
}

func (p poolSenderDo) Find() ([]*models.PoolSender, error) {
	result, err := p.DO.Find()
	return result.([]*models.PoolSender), err
}

func (p poolSenderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PoolSender, err error) {
	buf := make([]*models.PoolSender, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p poolSenderDo) FindInBatches(result *[]*models.PoolSender, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p poolSenderDo) Attrs(attrs ...field.AssignExpr) IPoolSenderDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p poolSenderDo) Assign(attrs ...field.AssignExpr) IPoolSenderDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p poolSenderDo) Joins(fields ...field.RelationField) IPoolSenderDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p poolSenderDo) Preload(fields ...field.RelationField) IPoolSenderDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p poolSenderDo) FirstOrInit() (*models.PoolSender, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.PoolSender), nil
	}
}

func (p poolSenderDo) FirstOrCreate() (*models.PoolSender, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.PoolSender), nil
	}
}

func (p poolSenderDo) FindByPage(offset int, limit int) (result []*models.PoolSender, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p poolSenderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p poolSenderDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p poolSenderDo) Delete(models ...*models.PoolSender) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *poolSenderDo) withDO(do gen.Dao) *poolSenderDo {
	p.DO = *do.(*gen.DO)
	return p
}
