// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"turbo-mailer-server/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newServerIPLog(db *gorm.DB, opts ...gen.DOOption) serverIPLog {
	_serverIPLog := serverIPLog{}

	_serverIPLog.serverIPLogDo.UseDB(db, opts...)
	_serverIPLog.serverIPLogDo.UseModel(&models.ServerIPLog{})

	tableName := _serverIPLog.serverIPLogDo.TableName()
	_serverIPLog.ALL = field.NewAsterisk(tableName)
	_serverIPLog.ID = field.NewUint(tableName, "id")
	_serverIPLog.ServerIP = field.NewString(tableName, "server_ip")
	_serverIPLog.Status = field.NewString(tableName, "status")
	_serverIPLog.Host = field.NewString(tableName, "host")
	_serverIPLog.CreatedAt = field.NewTime(tableName, "created_at")

	_serverIPLog.fillFieldMap()

	return _serverIPLog
}

type serverIPLog struct {
	serverIPLogDo serverIPLogDo

	ALL       field.Asterisk
	ID        field.Uint
	ServerIP  field.String
	Status    field.String
	Host      field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (s serverIPLog) Table(newTableName string) *serverIPLog {
	s.serverIPLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s serverIPLog) As(alias string) *serverIPLog {
	s.serverIPLogDo.DO = *(s.serverIPLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *serverIPLog) updateTableName(table string) *serverIPLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.ServerIP = field.NewString(table, "server_ip")
	s.Status = field.NewString(table, "status")
	s.Host = field.NewString(table, "host")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *serverIPLog) WithContext(ctx context.Context) IServerIPLogDo {
	return s.serverIPLogDo.WithContext(ctx)
}

func (s serverIPLog) TableName() string { return s.serverIPLogDo.TableName() }

func (s serverIPLog) Alias() string { return s.serverIPLogDo.Alias() }

func (s serverIPLog) Columns(cols ...field.Expr) gen.Columns { return s.serverIPLogDo.Columns(cols...) }

func (s *serverIPLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *serverIPLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["server_ip"] = s.ServerIP
	s.fieldMap["status"] = s.Status
	s.fieldMap["host"] = s.Host
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s serverIPLog) clone(db *gorm.DB) serverIPLog {
	s.serverIPLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s serverIPLog) replaceDB(db *gorm.DB) serverIPLog {
	s.serverIPLogDo.ReplaceDB(db)
	return s
}

type serverIPLogDo struct{ gen.DO }

type IServerIPLogDo interface {
	gen.SubQuery
	Debug() IServerIPLogDo
	WithContext(ctx context.Context) IServerIPLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IServerIPLogDo
	WriteDB() IServerIPLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IServerIPLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IServerIPLogDo
	Not(conds ...gen.Condition) IServerIPLogDo
	Or(conds ...gen.Condition) IServerIPLogDo
	Select(conds ...field.Expr) IServerIPLogDo
	Where(conds ...gen.Condition) IServerIPLogDo
	Order(conds ...field.Expr) IServerIPLogDo
	Distinct(cols ...field.Expr) IServerIPLogDo
	Omit(cols ...field.Expr) IServerIPLogDo
	Join(table schema.Tabler, on ...field.Expr) IServerIPLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IServerIPLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IServerIPLogDo
	Group(cols ...field.Expr) IServerIPLogDo
	Having(conds ...gen.Condition) IServerIPLogDo
	Limit(limit int) IServerIPLogDo
	Offset(offset int) IServerIPLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IServerIPLogDo
	Unscoped() IServerIPLogDo
	Create(values ...*models.ServerIPLog) error
	CreateInBatches(values []*models.ServerIPLog, batchSize int) error
	Save(values ...*models.ServerIPLog) error
	First() (*models.ServerIPLog, error)
	Take() (*models.ServerIPLog, error)
	Last() (*models.ServerIPLog, error)
	Find() ([]*models.ServerIPLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ServerIPLog, err error)
	FindInBatches(result *[]*models.ServerIPLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ServerIPLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IServerIPLogDo
	Assign(attrs ...field.AssignExpr) IServerIPLogDo
	Joins(fields ...field.RelationField) IServerIPLogDo
	Preload(fields ...field.RelationField) IServerIPLogDo
	FirstOrInit() (*models.ServerIPLog, error)
	FirstOrCreate() (*models.ServerIPLog, error)
	FindByPage(offset int, limit int) (result []*models.ServerIPLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IServerIPLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s serverIPLogDo) Debug() IServerIPLogDo {
	return s.withDO(s.DO.Debug())
}

func (s serverIPLogDo) WithContext(ctx context.Context) IServerIPLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s serverIPLogDo) ReadDB() IServerIPLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s serverIPLogDo) WriteDB() IServerIPLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s serverIPLogDo) Session(config *gorm.Session) IServerIPLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s serverIPLogDo) Clauses(conds ...clause.Expression) IServerIPLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s serverIPLogDo) Returning(value interface{}, columns ...string) IServerIPLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s serverIPLogDo) Not(conds ...gen.Condition) IServerIPLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s serverIPLogDo) Or(conds ...gen.Condition) IServerIPLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s serverIPLogDo) Select(conds ...field.Expr) IServerIPLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s serverIPLogDo) Where(conds ...gen.Condition) IServerIPLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s serverIPLogDo) Order(conds ...field.Expr) IServerIPLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s serverIPLogDo) Distinct(cols ...field.Expr) IServerIPLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s serverIPLogDo) Omit(cols ...field.Expr) IServerIPLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s serverIPLogDo) Join(table schema.Tabler, on ...field.Expr) IServerIPLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s serverIPLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IServerIPLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s serverIPLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IServerIPLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s serverIPLogDo) Group(cols ...field.Expr) IServerIPLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s serverIPLogDo) Having(conds ...gen.Condition) IServerIPLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s serverIPLogDo) Limit(limit int) IServerIPLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s serverIPLogDo) Offset(offset int) IServerIPLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s serverIPLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IServerIPLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s serverIPLogDo) Unscoped() IServerIPLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s serverIPLogDo) Create(values ...*models.ServerIPLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s serverIPLogDo) CreateInBatches(values []*models.ServerIPLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s serverIPLogDo) Save(values ...*models.ServerIPLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s serverIPLogDo) First() (*models.ServerIPLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ServerIPLog), nil
	}
}

func (s serverIPLogDo) Take() (*models.ServerIPLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ServerIPLog), nil
	}
}

func (s serverIPLogDo) Last() (*models.ServerIPLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ServerIPLog), nil
	}
}

func (s serverIPLogDo) Find() ([]*models.ServerIPLog, error) {
	result, err := s.DO.Find()
	return result.([]*models.ServerIPLog), err
}

func (s serverIPLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ServerIPLog, err error) {
	buf := make([]*models.ServerIPLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s serverIPLogDo) FindInBatches(result *[]*models.ServerIPLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s serverIPLogDo) Attrs(attrs ...field.AssignExpr) IServerIPLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s serverIPLogDo) Assign(attrs ...field.AssignExpr) IServerIPLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s serverIPLogDo) Joins(fields ...field.RelationField) IServerIPLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s serverIPLogDo) Preload(fields ...field.RelationField) IServerIPLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s serverIPLogDo) FirstOrInit() (*models.ServerIPLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ServerIPLog), nil
	}
}

func (s serverIPLogDo) FirstOrCreate() (*models.ServerIPLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ServerIPLog), nil
	}
}

func (s serverIPLogDo) FindByPage(offset int, limit int) (result []*models.ServerIPLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s serverIPLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s serverIPLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s serverIPLogDo) Delete(models ...*models.ServerIPLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *serverIPLogDo) withDO(do gen.Dao) *serverIPLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
