// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"turbo-mailer-server/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newServerIP(db *gorm.DB, opts ...gen.DOOption) serverIP {
	_serverIP := serverIP{}

	_serverIP.serverIPDo.UseDB(db, opts...)
	_serverIP.serverIPDo.UseModel(&models.ServerIP{})

	tableName := _serverIP.serverIPDo.TableName()
	_serverIP.ALL = field.NewAsterisk(tableName)
	_serverIP.ID = field.NewUint(tableName, "id")
	_serverIP.CreatedAt = field.NewTime(tableName, "created_at")
	_serverIP.UpdatedAt = field.NewTime(tableName, "updated_at")
	_serverIP.DeletedAt = field.NewField(tableName, "deleted_at")
	_serverIP.IP = field.NewString(tableName, "ip")
	_serverIP.LastActiveAt = field.NewTime(tableName, "last_active_at")

	_serverIP.fillFieldMap()

	return _serverIP
}

type serverIP struct {
	serverIPDo serverIPDo

	ALL          field.Asterisk
	ID           field.Uint
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field
	IP           field.String
	LastActiveAt field.Time

	fieldMap map[string]field.Expr
}

func (s serverIP) Table(newTableName string) *serverIP {
	s.serverIPDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s serverIP) As(alias string) *serverIP {
	s.serverIPDo.DO = *(s.serverIPDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *serverIP) updateTableName(table string) *serverIP {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.IP = field.NewString(table, "ip")
	s.LastActiveAt = field.NewTime(table, "last_active_at")

	s.fillFieldMap()

	return s
}

func (s *serverIP) WithContext(ctx context.Context) IServerIPDo { return s.serverIPDo.WithContext(ctx) }

func (s serverIP) TableName() string { return s.serverIPDo.TableName() }

func (s serverIP) Alias() string { return s.serverIPDo.Alias() }

func (s serverIP) Columns(cols ...field.Expr) gen.Columns { return s.serverIPDo.Columns(cols...) }

func (s *serverIP) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *serverIP) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["ip"] = s.IP
	s.fieldMap["last_active_at"] = s.LastActiveAt
}

func (s serverIP) clone(db *gorm.DB) serverIP {
	s.serverIPDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s serverIP) replaceDB(db *gorm.DB) serverIP {
	s.serverIPDo.ReplaceDB(db)
	return s
}

type serverIPDo struct{ gen.DO }

type IServerIPDo interface {
	gen.SubQuery
	Debug() IServerIPDo
	WithContext(ctx context.Context) IServerIPDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IServerIPDo
	WriteDB() IServerIPDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IServerIPDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IServerIPDo
	Not(conds ...gen.Condition) IServerIPDo
	Or(conds ...gen.Condition) IServerIPDo
	Select(conds ...field.Expr) IServerIPDo
	Where(conds ...gen.Condition) IServerIPDo
	Order(conds ...field.Expr) IServerIPDo
	Distinct(cols ...field.Expr) IServerIPDo
	Omit(cols ...field.Expr) IServerIPDo
	Join(table schema.Tabler, on ...field.Expr) IServerIPDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IServerIPDo
	RightJoin(table schema.Tabler, on ...field.Expr) IServerIPDo
	Group(cols ...field.Expr) IServerIPDo
	Having(conds ...gen.Condition) IServerIPDo
	Limit(limit int) IServerIPDo
	Offset(offset int) IServerIPDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IServerIPDo
	Unscoped() IServerIPDo
	Create(values ...*models.ServerIP) error
	CreateInBatches(values []*models.ServerIP, batchSize int) error
	Save(values ...*models.ServerIP) error
	First() (*models.ServerIP, error)
	Take() (*models.ServerIP, error)
	Last() (*models.ServerIP, error)
	Find() ([]*models.ServerIP, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ServerIP, err error)
	FindInBatches(result *[]*models.ServerIP, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ServerIP) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IServerIPDo
	Assign(attrs ...field.AssignExpr) IServerIPDo
	Joins(fields ...field.RelationField) IServerIPDo
	Preload(fields ...field.RelationField) IServerIPDo
	FirstOrInit() (*models.ServerIP, error)
	FirstOrCreate() (*models.ServerIP, error)
	FindByPage(offset int, limit int) (result []*models.ServerIP, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IServerIPDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s serverIPDo) Debug() IServerIPDo {
	return s.withDO(s.DO.Debug())
}

func (s serverIPDo) WithContext(ctx context.Context) IServerIPDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s serverIPDo) ReadDB() IServerIPDo {
	return s.Clauses(dbresolver.Read)
}

func (s serverIPDo) WriteDB() IServerIPDo {
	return s.Clauses(dbresolver.Write)
}

func (s serverIPDo) Session(config *gorm.Session) IServerIPDo {
	return s.withDO(s.DO.Session(config))
}

func (s serverIPDo) Clauses(conds ...clause.Expression) IServerIPDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s serverIPDo) Returning(value interface{}, columns ...string) IServerIPDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s serverIPDo) Not(conds ...gen.Condition) IServerIPDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s serverIPDo) Or(conds ...gen.Condition) IServerIPDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s serverIPDo) Select(conds ...field.Expr) IServerIPDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s serverIPDo) Where(conds ...gen.Condition) IServerIPDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s serverIPDo) Order(conds ...field.Expr) IServerIPDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s serverIPDo) Distinct(cols ...field.Expr) IServerIPDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s serverIPDo) Omit(cols ...field.Expr) IServerIPDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s serverIPDo) Join(table schema.Tabler, on ...field.Expr) IServerIPDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s serverIPDo) LeftJoin(table schema.Tabler, on ...field.Expr) IServerIPDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s serverIPDo) RightJoin(table schema.Tabler, on ...field.Expr) IServerIPDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s serverIPDo) Group(cols ...field.Expr) IServerIPDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s serverIPDo) Having(conds ...gen.Condition) IServerIPDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s serverIPDo) Limit(limit int) IServerIPDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s serverIPDo) Offset(offset int) IServerIPDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s serverIPDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IServerIPDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s serverIPDo) Unscoped() IServerIPDo {
	return s.withDO(s.DO.Unscoped())
}

func (s serverIPDo) Create(values ...*models.ServerIP) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s serverIPDo) CreateInBatches(values []*models.ServerIP, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s serverIPDo) Save(values ...*models.ServerIP) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s serverIPDo) First() (*models.ServerIP, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ServerIP), nil
	}
}

func (s serverIPDo) Take() (*models.ServerIP, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ServerIP), nil
	}
}

func (s serverIPDo) Last() (*models.ServerIP, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ServerIP), nil
	}
}

func (s serverIPDo) Find() ([]*models.ServerIP, error) {
	result, err := s.DO.Find()
	return result.([]*models.ServerIP), err
}

func (s serverIPDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ServerIP, err error) {
	buf := make([]*models.ServerIP, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s serverIPDo) FindInBatches(result *[]*models.ServerIP, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s serverIPDo) Attrs(attrs ...field.AssignExpr) IServerIPDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s serverIPDo) Assign(attrs ...field.AssignExpr) IServerIPDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s serverIPDo) Joins(fields ...field.RelationField) IServerIPDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s serverIPDo) Preload(fields ...field.RelationField) IServerIPDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s serverIPDo) FirstOrInit() (*models.ServerIP, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ServerIP), nil
	}
}

func (s serverIPDo) FirstOrCreate() (*models.ServerIP, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ServerIP), nil
	}
}

func (s serverIPDo) FindByPage(offset int, limit int) (result []*models.ServerIP, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s serverIPDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s serverIPDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s serverIPDo) Delete(models ...*models.ServerIP) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *serverIPDo) withDO(do gen.Dao) *serverIPDo {
	s.DO = *do.(*gen.DO)
	return s
}
