// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"turbo-mailer-server/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newTaskLogArchive(db *gorm.DB, opts ...gen.DOOption) taskLogArchive {
	_taskLogArchive := taskLogArchive{}

	_taskLogArchive.taskLogArchiveDo.UseDB(db, opts...)
	_taskLogArchive.taskLogArchiveDo.UseModel(&models.TaskLogArchive{})

	tableName := _taskLogArchive.taskLogArchiveDo.TableName()
	_taskLogArchive.ALL = field.NewAsterisk(tableName)
	_taskLogArchive.ID = field.NewUint(tableName, "id")
	_taskLogArchive.TaskID = field.NewUint(tableName, "task_id")
	_taskLogArchive.PoolID = field.NewUint(tableName, "pool_id")
	_taskLogArchive.Sender = field.NewString(tableName, "sender")
	_taskLogArchive.Receiver = field.NewString(tableName, "receiver")
	_taskLogArchive.State = field.NewString(tableName, "state")
	_taskLogArchive.Message = field.NewString(tableName, "message")
	_taskLogArchive.CreatedAt = field.NewTime(tableName, "created_at")
	_taskLogArchive.ArchivedAt = field.NewTime(tableName, "archived_at")

	_taskLogArchive.fillFieldMap()

	return _taskLogArchive
}

type taskLogArchive struct {
	taskLogArchiveDo taskLogArchiveDo

	ALL        field.Asterisk
	ID         field.Uint
	TaskID     field.Uint
	PoolID     field.Uint
	Sender     field.String
	Receiver   field.String
	State      field.String
	Message    field.String
	CreatedAt  field.Time
	ArchivedAt field.Time

	fieldMap map[string]field.Expr
}

func (t taskLogArchive) Table(newTableName string) *taskLogArchive {
	t.taskLogArchiveDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t taskLogArchive) As(alias string) *taskLogArchive {
	t.taskLogArchiveDo.DO = *(t.taskLogArchiveDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *taskLogArchive) updateTableName(table string) *taskLogArchive {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint(table, "id")
	t.TaskID = field.NewUint(table, "task_id")
	t.PoolID = field.NewUint(table, "pool_id")
	t.Sender = field.NewString(table, "sender")
	t.Receiver = field.NewString(table, "receiver")
	t.State = field.NewString(table, "state")
	t.Message = field.NewString(table, "message")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.ArchivedAt = field.NewTime(table, "archived_at")

	t.fillFieldMap()

	return t
}

func (t *taskLogArchive) WithContext(ctx context.Context) ITaskLogArchiveDo {
	return t.taskLogArchiveDo.WithContext(ctx)
}

func (t taskLogArchive) TableName() string { return t.taskLogArchiveDo.TableName() }

func (t taskLogArchive) Alias() string { return t.taskLogArchiveDo.Alias() }

func (t taskLogArchive) Columns(cols ...field.Expr) gen.Columns {
	return t.taskLogArchiveDo.Columns(cols...)
}

func (t *taskLogArchive) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *taskLogArchive) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["id"] = t.ID
	t.fieldMap["task_id"] = t.TaskID
	t.fieldMap["pool_id"] = t.PoolID
	t.fieldMap["sender"] = t.Sender
	t.fieldMap["receiver"] = t.Receiver
	t.fieldMap["state"] = t.State
	t.fieldMap["message"] = t.Message
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["archived_at"] = t.ArchivedAt
}

func (t taskLogArchive) clone(db *gorm.DB) taskLogArchive {
	t.taskLogArchiveDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t taskLogArchive) replaceDB(db *gorm.DB) taskLogArchive {
	t.taskLogArchiveDo.ReplaceDB(db)
	return t
}

type taskLogArchiveDo struct{ gen.DO }

type ITaskLogArchiveDo interface {
	gen.SubQuery
	Debug() ITaskLogArchiveDo
	WithContext(ctx context.Context) ITaskLogArchiveDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITaskLogArchiveDo
	WriteDB() ITaskLogArchiveDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITaskLogArchiveDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITaskLogArchiveDo
	Not(conds ...gen.Condition) ITaskLogArchiveDo
	Or(conds ...gen.Condition) ITaskLogArchiveDo
	Select(conds ...field.Expr) ITaskLogArchiveDo
	Where(conds ...gen.Condition) ITaskLogArchiveDo
	Order(conds ...field.Expr) ITaskLogArchiveDo
	Distinct(cols ...field.Expr) ITaskLogArchiveDo
	Omit(cols ...field.Expr) ITaskLogArchiveDo
	Join(table schema.Tabler, on ...field.Expr) ITaskLogArchiveDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITaskLogArchiveDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITaskLogArchiveDo
	Group(cols ...field.Expr) ITaskLogArchiveDo
	Having(conds ...gen.Condition) ITaskLogArchiveDo
	Limit(limit int) ITaskLogArchiveDo
	Offset(offset int) ITaskLogArchiveDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskLogArchiveDo
	Unscoped() ITaskLogArchiveDo
	Create(values ...*models.TaskLogArchive) error
	CreateInBatches(values []*models.TaskLogArchive, batchSize int) error
	Save(values ...*models.TaskLogArchive) error
	First() (*models.TaskLogArchive, error)
	Take() (*models.TaskLogArchive, error)
	Last() (*models.TaskLogArchive, error)
	Find() ([]*models.TaskLogArchive, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TaskLogArchive, err error)
	FindInBatches(result *[]*models.TaskLogArchive, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.TaskLogArchive) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITaskLogArchiveDo
	Assign(attrs ...field.AssignExpr) ITaskLogArchiveDo
	Joins(fields ...field.RelationField) ITaskLogArchiveDo
	Preload(fields ...field.RelationField) ITaskLogArchiveDo
	FirstOrInit() (*models.TaskLogArchive, error)
	FirstOrCreate() (*models.TaskLogArchive, error)
	FindByPage(offset int, limit int) (result []*models.TaskLogArchive, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITaskLogArchiveDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t taskLogArchiveDo) Debug() ITaskLogArchiveDo {
	return t.withDO(t.DO.Debug())
}

func (t taskLogArchiveDo) WithContext(ctx context.Context) ITaskLogArchiveDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taskLogArchiveDo) ReadDB() ITaskLogArchiveDo {
	return t.Clauses(dbresolver.Read)
}

func (t taskLogArchiveDo) WriteDB() ITaskLogArchiveDo {
	return t.Clauses(dbresolver.Write)
}

func (t taskLogArchiveDo) Session(config *gorm.Session) ITaskLogArchiveDo {
	return t.withDO(t.DO.Session(config))
}

func (t taskLogArchiveDo) Clauses(conds ...clause.Expression) ITaskLogArchiveDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taskLogArchiveDo) Returning(value interface{}, columns ...string) ITaskLogArchiveDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taskLogArchiveDo) Not(conds ...gen.Condition) ITaskLogArchiveDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taskLogArchiveDo) Or(conds ...gen.Condition) ITaskLogArchiveDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taskLogArchiveDo) Select(conds ...field.Expr) ITaskLogArchiveDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taskLogArchiveDo) Where(conds ...gen.Condition) ITaskLogArchiveDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taskLogArchiveDo) Order(conds ...field.Expr) ITaskLogArchiveDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taskLogArchiveDo) Distinct(cols ...field.Expr) ITaskLogArchiveDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taskLogArchiveDo) Omit(cols ...field.Expr) ITaskLogArchiveDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taskLogArchiveDo) Join(table schema.Tabler, on ...field.Expr) ITaskLogArchiveDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taskLogArchiveDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITaskLogArchiveDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taskLogArchiveDo) RightJoin(table schema.Tabler, on ...field.Expr) ITaskLogArchiveDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taskLogArchiveDo) Group(cols ...field.Expr) ITaskLogArchiveDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taskLogArchiveDo) Having(conds ...gen.Condition) ITaskLogArchiveDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taskLogArchiveDo) Limit(limit int) ITaskLogArchiveDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taskLogArchiveDo) Offset(offset int) ITaskLogArchiveDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taskLogArchiveDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskLogArchiveDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taskLogArchiveDo) Unscoped() ITaskLogArchiveDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taskLogArchiveDo) Create(values ...*models.TaskLogArchive) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taskLogArchiveDo) CreateInBatches(values []*models.TaskLogArchive, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taskLogArchiveDo) Save(values ...*models.TaskLogArchive) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taskLogArchiveDo) First() (*models.TaskLogArchive, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskLogArchive), nil
	}
}

func (t taskLogArchiveDo) Take() (*models.TaskLogArchive, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskLogArchive), nil
	}
}

func (t taskLogArchiveDo) Last() (*models.TaskLogArchive, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskLogArchive), nil
	}
}

func (t taskLogArchiveDo) Find() ([]*models.TaskLogArchive, error) {
	result, err := t.DO.Find()
	return result.([]*models.TaskLogArchive), err
}

func (t taskLogArchiveDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TaskLogArchive, err error) {
	buf := make([]*models.TaskLogArchive, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taskLogArchiveDo) FindInBatches(result *[]*models.TaskLogArchive, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taskLogArchiveDo) Attrs(attrs ...field.AssignExpr) ITaskLogArchiveDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taskLogArchiveDo) Assign(attrs ...field.AssignExpr) ITaskLogArchiveDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taskLogArchiveDo) Joins(fields ...field.RelationField) ITaskLogArchiveDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taskLogArchiveDo) Preload(fields ...field.RelationField) ITaskLogArchiveDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taskLogArchiveDo) FirstOrInit() (*models.TaskLogArchive, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskLogArchive), nil
	}
}

func (t taskLogArchiveDo) FirstOrCreate() (*models.TaskLogArchive, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskLogArchive), nil
	}
}

func (t taskLogArchiveDo) FindByPage(offset int, limit int) (result []*models.TaskLogArchive, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taskLogArchiveDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taskLogArchiveDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taskLogArchiveDo) Delete(models ...*models.TaskLogArchive) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taskLogArchiveDo) withDO(do gen.Dao) *taskLogArchiveDo {
	t.DO = *do.(*gen.DO)
	return t
}
