// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"turbo-mailer-server/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newTaskPool(db *gorm.DB, opts ...gen.DOOption) taskPool {
	_taskPool := taskPool{}

	_taskPool.taskPoolDo.UseDB(db, opts...)
	_taskPool.taskPoolDo.UseModel(&models.TaskPool{})

	tableName := _taskPool.taskPoolDo.TableName()
	_taskPool.ALL = field.NewAsterisk(tableName)
	_taskPool.TaskID = field.NewUint(tableName, "task_id")
	_taskPool.PoolID = field.NewUint(tableName, "pool_id")
	_taskPool.Weight = field.NewInt(tableName, "weight")

	_taskPool.fillFieldMap()

	return _taskPool
}

type taskPool struct {
	taskPoolDo taskPoolDo

	ALL    field.Asterisk
	TaskID field.Uint
	PoolID field.Uint
	Weight field.Int

	fieldMap map[string]field.Expr
}

func (t taskPool) Table(newTableName string) *taskPool {
	t.taskPoolDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t taskPool) As(alias string) *taskPool {
	t.taskPoolDo.DO = *(t.taskPoolDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *taskPool) updateTableName(table string) *taskPool {
	t.ALL = field.NewAsterisk(table)
	t.TaskID = field.NewUint(table, "task_id")
	t.PoolID = field.NewUint(table, "pool_id")
	t.Weight = field.NewInt(table, "weight")

	t.fillFieldMap()

	return t
}

func (t *taskPool) WithContext(ctx context.Context) ITaskPoolDo { return t.taskPoolDo.WithContext(ctx) }

func (t taskPool) TableName() string { return t.taskPoolDo.TableName() }

func (t taskPool) Alias() string { return t.taskPoolDo.Alias() }

func (t taskPool) Columns(cols ...field.Expr) gen.Columns { return t.taskPoolDo.Columns(cols...) }

func (t *taskPool) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *taskPool) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["task_id"] = t.TaskID
	t.fieldMap["pool_id"] = t.PoolID
	t.fieldMap["weight"] = t.Weight
}

func (t taskPool) clone(db *gorm.DB) taskPool {
	t.taskPoolDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t taskPool) replaceDB(db *gorm.DB) taskPool {
	t.taskPoolDo.ReplaceDB(db)
	return t
}

type taskPoolDo struct{ gen.DO }

type ITaskPoolDo interface {
	gen.SubQuery
	Debug() ITaskPoolDo
	WithContext(ctx context.Context) ITaskPoolDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITaskPoolDo
	WriteDB() ITaskPoolDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITaskPoolDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITaskPoolDo
	Not(conds ...gen.Condition) ITaskPoolDo
	Or(conds ...gen.Condition) ITaskPoolDo
	Select(conds ...field.Expr) ITaskPoolDo
	Where(conds ...gen.Condition) ITaskPoolDo
	Order(conds ...field.Expr) ITaskPoolDo
	Distinct(cols ...field.Expr) ITaskPoolDo
	Omit(cols ...field.Expr) ITaskPoolDo
	Join(table schema.Tabler, on ...field.Expr) ITaskPoolDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITaskPoolDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITaskPoolDo
	Group(cols ...field.Expr) ITaskPoolDo
	Having(conds ...gen.Condition) ITaskPoolDo
	Limit(limit int) ITaskPoolDo
	Offset(offset int) ITaskPoolDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskPoolDo
	Unscoped() ITaskPoolDo
	Create(values ...*models.TaskPool) error
	CreateInBatches(values []*models.TaskPool, batchSize int) error
	Save(values ...*models.TaskPool) error
	First() (*models.TaskPool, error)
	Take() (*models.TaskPool, error)
	Last() (*models.TaskPool, error)
	Find() ([]*models.TaskPool, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TaskPool, err error)
	FindInBatches(result *[]*models.TaskPool, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.TaskPool) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITaskPoolDo
	Assign(attrs ...field.AssignExpr) ITaskPoolDo
	Joins(fields ...field.RelationField) ITaskPoolDo
	Preload(fields ...field.RelationField) ITaskPoolDo
	FirstOrInit() (*models.TaskPool, error)
	FirstOrCreate() (*models.TaskPool, error)
	FindByPage(offset int, limit int) (result []*models.TaskPool, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITaskPoolDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t taskPoolDo) Debug() ITaskPoolDo {
	return t.withDO(t.DO.Debug())
}

func (t taskPoolDo) WithContext(ctx context.Context) ITaskPoolDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taskPoolDo) ReadDB() ITaskPoolDo {
	return t.Clauses(dbresolver.Read)
}

func (t taskPoolDo) WriteDB() ITaskPoolDo {
	return t.Clauses(dbresolver.Write)
}

func (t taskPoolDo) Session(config *gorm.Session) ITaskPoolDo {
	return t.withDO(t.DO.Session(config))
}

func (t taskPoolDo) Clauses(conds ...clause.Expression) ITaskPoolDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taskPoolDo) Returning(value interface{}, columns ...string) ITaskPoolDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taskPoolDo) Not(conds ...gen.Condition) ITaskPoolDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taskPoolDo) Or(conds ...gen.Condition) ITaskPoolDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taskPoolDo) Select(conds ...field.Expr) ITaskPoolDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taskPoolDo) Where(conds ...gen.Condition) ITaskPoolDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taskPoolDo) Order(conds ...field.Expr) ITaskPoolDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taskPoolDo) Distinct(cols ...field.Expr) ITaskPoolDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taskPoolDo) Omit(cols ...field.Expr) ITaskPoolDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taskPoolDo) Join(table schema.Tabler, on ...field.Expr) ITaskPoolDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taskPoolDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITaskPoolDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taskPoolDo) RightJoin(table schema.Tabler, on ...field.Expr) ITaskPoolDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taskPoolDo) Group(cols ...field.Expr) ITaskPoolDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taskPoolDo) Having(conds ...gen.Condition) ITaskPoolDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taskPoolDo) Limit(limit int) ITaskPoolDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taskPoolDo) Offset(offset int) ITaskPoolDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taskPoolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskPoolDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taskPoolDo) Unscoped() ITaskPoolDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taskPoolDo) Create(values ...*models.TaskPool) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taskPoolDo) CreateInBatches(values []*models.TaskPool, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taskPoolDo) Save(values ...*models.TaskPool) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taskPoolDo) First() (*models.TaskPool, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskPool), nil
	}
}

func (t taskPoolDo) Take() (*models.TaskPool, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskPool), nil
	}
}

func (t taskPoolDo) Last() (*models.TaskPool, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskPool), nil
	}
}

func (t taskPoolDo) Find() ([]*models.TaskPool, error) {
	result, err := t.DO.Find()
	return result.([]*models.TaskPool), err
}

func (t taskPoolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TaskPool, err error) {
	buf := make([]*models.TaskPool, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taskPoolDo) FindInBatches(result *[]*models.TaskPool, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taskPoolDo) Attrs(attrs ...field.AssignExpr) ITaskPoolDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taskPoolDo) Assign(attrs ...field.AssignExpr) ITaskPoolDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taskPoolDo) Joins(fields ...field.RelationField) ITaskPoolDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taskPoolDo) Preload(fields ...field.RelationField) ITaskPoolDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taskPoolDo) FirstOrInit() (*models.TaskPool, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskPool), nil
	}
}

func (t taskPoolDo) FirstOrCreate() (*models.TaskPool, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TaskPool), nil
	}
}

func (t taskPoolDo) FindByPage(offset int, limit int) (result []*models.TaskPool, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taskPoolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taskPoolDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taskPoolDo) Delete(models ...*models.TaskPool) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taskPoolDo) withDO(do gen.Dao) *taskPoolDo {
	t.DO = *do.(*gen.DO)
	return t
}
