apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
    app.kubernetes.io/component: postfix
    domain: {{ tpl .Values.domain . | quote }}
spec:
  # postfix is a single instance service
  replicas: 1
  selector:
    matchLabels:
      {{- include "postfix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postfix
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postfix.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: postfix
        config/checksum: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha1sum }}
        domain: {{ tpl .Values.domain . | quote }}
    spec:
      terminationGracePeriodSeconds: 5
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.checkDNS.enabled }}
        - name: {{ .Chart.Name }}-check-dns
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ if eq (.Values.image.tag | default .Chart.AppVersion) "latest" }}Always{{ else }}{{ .Values.image.pullPolicy }}{{ end }}
          command: ["python3"]
          args:
            - "-c"
            - |
              import dns.resolver
              import requests
              import os
              import time

              domain = "{{ .Values.domain }}"
              max_attempts = 60
              delay = 30

              def get_external_ip():
                  try:
                      response = requests.get('https://api.ipify.org')
                      return response.text
                  except Exception as e:
                      print(f"Error getting external IP: {str(e)}")
                      return None

              def check_spf_record(domain, external_ip):
                  try:
                      answers = dns.resolver.resolve(domain, 'TXT')
                      spf_record = next((str(rdata) for rdata in answers for txt in rdata.strings if txt.startswith(b'v=spf1')), None)

                      if spf_record:
                          if f"ip4:{external_ip}" in spf_record:
                              print(f"SPF record for {domain} includes the current external IP: {external_ip}")
                              return True
                          else:
                              print(f"Error: SPF record for {domain} does not include the current external IP: {external_ip}")
                              print(f"Current SPF record: {spf_record}")
                              return False
                      else:
                          print(f"Error: No SPF record found for {domain}")
                          return False
                  except Exception as e:
                      print(f"Error checking SPF record: {str(e)}")
                      return False

              for attempt in range(max_attempts):
                  external_ip = get_external_ip()
                  if not external_ip:
                      print("Failed to get external IP")
                      time.sleep(delay)
                      continue

                  print(f"Current external IP: {external_ip}")

                  if check_spf_record(domain, external_ip):
                      exit(0)

                  if attempt < max_attempts - 1:
                      print(f"Attempt {attempt + 1} failed. Retrying in {delay} seconds...")
                      time.sleep(delay)
                  else:
                      print(f"All {max_attempts} attempts failed. Exiting with error.")
                      exit(1)
        {{- end }}
        - name: {{ .Chart.Name }}-set-permissions
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ if eq (.Values.image.tag | default .Chart.AppVersion) "latest" }}Always{{ else }}{{ .Values.image.pullPolicy }}{{ end }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp -L /etc/postfix/main.cf /config/main.cf
              cp -L /etc/opendkim.conf /config/opendkim.conf
              chown root:root /config/main.cf
              chown root:root /config/opendkim.conf
              chmod 600 /config/main.cf /config/opendkim.conf

              {{- if .Values.dkimPrivateKey }}
              cp -r -L /etc/dkimkeys /config/dkimkeys
              chown -R root:root /config/dkimkeys
              chmod -R 700 /config/dkimkeys
              {{- else }}
              chown -R root:root /etc/dkimkeys
              chmod -R 700 /etc/dkimkeys
              {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/postfix/main.cf
              subPath: main.cf
            - name: opendkim
              mountPath: /etc/opendkim.conf
              subPath: opendkim.conf
            - name: dkimkeys
              mountPath: /etc/dkimkeys
            - name: shared-config
              mountPath: /config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ if eq (.Values.image.tag | default .Chart.AppVersion) "latest" }}Always{{ else }}{{ .Values.image.pullPolicy }}{{ end }}
          env:
            - name: DOMAIN
              value: {{ .Values.domain }}
          ports:
            - name: smtp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # command: ["/bin/sh", "-c"]
          # args:
          #   - |
          #     # tail -f /dev/null

          #     apt-get update && apt-get install -y rsyslog

          #     # echo "*.* /dev/stdout" > /etc/rsyslog.conf
          #     # rsyslogd || true


          #     [ ! -f /var/spool/postfix/etc/resolv.conf ] && cp /etc/resolv.conf /var/spool/postfix/etc/resolv.conf || true
          #     # /usr/sbin/opendkim -u root
          #     # /usr/sbin/postfix start-fg

          #     service postfix start
          #     service opendkim start

          #     rsyslogd -n
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          volumeMounts:
            - name: shared-config
              mountPath: /etc/postfix/main.cf
              subPath: main.cf
            - name: shared-config
              mountPath: /etc/opendkim.conf
              subPath: opendkim.conf
            {{- if .Values.dkimPrivateKey }}
            - name: shared-config
              mountPath: /etc/dkimkeys
              subPath: dkimkeys
            {{- else }}
            - name: dkimkeys
              mountPath: /etc/dkimkeys
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "postfix.fullname" . }}
        - name: dkimkeys
          {{- if .Values.dkimPrivateKey }}
          secret:
            secretName: {{ include "postfix.fullname" . }}-dkimkeys
          {{- else }}
          hostPath:
            path: /etc/dkimkeys/{{ .Values.domain }}
            type: DirectoryOrCreate
          {{- end }}
        - name: opendkim
          configMap:
            name: {{ include "postfix.fullname" . }}
            items:
              - key: opendkim.conf
                path: opendkim.conf
        - name: shared-config
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
