{{- if .Values.dkimPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postfix.fullname" . }}-dkimkeys
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
    app.kubernetes.io/component: postfix
type: Opaque
data:
  mail.private: {{ .Values.dkimPrivateKey | b64enc | quote }}
{{- end }}
