{{- if .Values.dkimPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postfix.fullname" . }}-dkimkeys
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
    app.kubernetes.io/component: postfix
type: Opaque
data:
  mail.pem: {{ .Values.dkimPrivateKey | b64enc | quote }}
{{- end }}

---

{{- if and .Values.setupDNS.enabled (ne .Values.setupDNS.config "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postfix.fullname" . }}-setup-dns
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
    app.kubernetes.io/component: postfix
type: Opaque
data:
  config.yaml: {{ .Values.setupDNS.config | b64enc | quote }}
{{- end }}
