apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.smtp.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: {{ .Values.service.smtp_tls.port }}
      targetPort: smtp-tls
      protocol: TCP
      name: smtp-tls
  selector:
    {{- include "postfix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postfix
