helmDefaults:
  createNamespace: true
  atomic: true
  timeout: 300
  wait: true

environments:
  dev:
    values:
      - deploy/env-dev.yaml
  test:
    values:
      - deploy/env-test.yaml
  prod:
    values:
      - deploy/env-prod.yaml

---

releases:
  - name: turbo-mailer
    namespace: turbo-mailer-{{ .Environment.Name }}
    chart: ./charts/turbo-mailer
    values:
      - deploy/values-{{ .Environment.Name }}.yaml
      - api:
          config: |
            {{- $.Values.config | nindent 12 }}
      - worker:
          domains:
            {{- range .Values.domains }}
            - {{ .domain }}
            {{- end }}

  {{- range .Values.domains }}
  - name: postfix-{{ .domain | sha1sum | trunc 8 }}
    namespace: turbo-mailer-{{ $.Environment.Name }}
    chart: ./charts/postfix
    values:
      - deploy/values-postfix-{{ $.Environment.Name }}.yaml
      - image:
          tag: latest
        checkDNS:
          enabled: false
        setupDNS:
          enabled: true
        {{- if and (hasKey . "dkimPrivateKey") .dkimPrivateKey }}
        dkimPrivateKey: |
          {{- printf "\n%s" .dkimPrivateKey | indent 10 }}
        {{- end }}
        replicaCount: {{ len .server_labels }}
        domain: {{ .domain }}
        cloudflare:
          {{- if hasKey . "api_key" }}
          api_key: {{ .api_key }}
          {{- else if hasKey $.Values "cloudflare" }}
          api_key: {{ $.Values.cloudflare.api_key }}
          {{- end }}
          {{- if hasKey . "zone_id" }}
          zone_id: {{ .zone_id }}
          {{- end }}
        {{- if .server_labels }}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    {{- range .server_labels }}
                    - {key: {{ . }}, operator: Exists}
                    {{- end }}
        {{- end }}
  {{- end }}

