helmDefaults:
  createNamespace: true
  atomic: true
  timeout: 600

environments:
  dev:
  test:
  prod:

---

releases:
  - name: turbo-mailer
    namespace: turbo-mailer-{{ .Environment.Name }}
    chart: ./charts/turbo-mailer
    values:
      - deploy/values-{{ .Environment.Name }}.yaml
