helmDefaults:
  createNamespace: true
  atomic: true
  timeout: 300

environments:
  dev:
    values:
      - deploy/env-dev.yaml
  test:
    values:
      - deploy/env-test.yaml
  prod:
    values:
      - deploy/env-prod.yaml

---

releases:
  - name: turbo-mailer
    namespace: turbo-mailer-{{ .Environment.Name }}
    chart: ./charts/turbo-mailer
    values:
      - deploy/values-{{ .Environment.Name }}.yaml
      - api:
          config: |
            {{- $.Values.config | nindent 12 }}
      - worker:
          domains:
            {{- range .Values.emailDomains }}
            - {{ .domain }}
            {{- end }}

  {{- range .Values.emailDomains }}
  - name: postfix-{{ .domain | sha1sum | trunc 8 }}
    namespace: turbo-mailer-{{ $.Environment.Name }}
    chart: ./charts/postfix
    values:
      - deploy/values-postfix-{{ $.Environment.Name }}.yaml
      - image:
          tag: latest
        checkDNS:
          enabled: false
        setupDNS:
          enabled: true
          config: |
            {{- $.Values.config | nindent 12 }}
        {{- if and (hasKey . "dkimPrivateKey") .dkimPrivateKey }}
        dkimPrivateKey: |
          {{- printf "\n%s" .dkimPrivateKey | indent 10 }}
        {{- end }}
        replicaCount: {{ len .serverLabels }}
        domain: {{ .domain }}
        {{- if .serverLabels }}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    {{- range .serverLabels }}
                    - {key: {{ . }}, operator: Exists}
                    {{- end }}
        {{- end }}
  {{- end }}

