frontend:
  replicaCount: 1

  image:
    repository: yinheli/turbo-mailer-frontend
    pullPolicy: Always
    tag: "develop"

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - host: dashboard-test.turbomx.org
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - secretName: turbo-mailer-tls
      hosts:
      - dashboard-test.turbomx.org

api:
  replicaCount: 1

  image:
    repository: yinheli/turbo-mailer-server
    pullPolicy: Always
    tag: "develop"

worker:
  replicaCount: 1

  image:
    repository: yinheli/turbo-mailer-server
    pullPolicy: Always
    tag: "develop"

