frontend:
  replicaCount: 2

  image:
    repository: turbo-mailer-frontend
    pullPolicy: Always
    tag: ""

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: dashboard.turbomx.org
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: turbo-mailer-tls
        hosts:
          - dashboard.turbomx.org

api:
  replicaCount: 2

  image:
    repository: turbo-mailer-server
    pullPolicy: Always
    tag: ""

worker:
  replicaCount: 4

  image:
    repository: turbo-mailer-server
    pullPolicy: Always
    tag: ""


dispatcher:
  replicaCount: 1

  image:
    repository: turbo-mailer-server
    pullPolicy: Always
    tag: ""
