helmfiles:
  - path: ../common/helmfile.yaml

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx


releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    installed: true
    chart: ingress-nginx/ingress-nginx
    values:
      - values.yaml

