exporters:
  otlphttp/openobserve:
    endpoint: http://openobserve-openobserve-standalone.openobserve.svc:5080/api/default
    headers:
      Authorization: Basic YWRtaW5AdHVyYm9teC5vcmc6RjVKNlpjVmtnU0RTaHJBQg==
  otlphttp/openobserve_k8s_events:
    endpoint: https://openobserve-openobserve-standalone.openobserve.svc:5080/api/default
    headers:
      Authorization: Basic YWRtaW5AdHVyYm9teC5vcmc6RjVKNlpjVmtnU0RTaHJBQg==
      stream-name: k8s_events
