sha: "ec5fea3d28ddcf0134c7fe5e283ace1c2369a98b"

frontend:
  replicaCount: 1

  image:
    repository: turbo-mailer-frontend
    pullPolicy: Always
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}

api:
  replicaCount: 1

  image:
    repository: turbo-mailer-server
    pullPolicy: Always
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 5000

  resources: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}

  config: |
    server:
      address: :5000

    database:
      turbo-mailer:
        uri: "postgres://turbomailer:password@turbo-mailer-postgresql:5432/turbo-mailer?sslmode=disable"

    redis:
      turbo-mailer:
        name: "turbo-mailer"
        addr: "turbo-mailer-redis-master:6379"
        password: "password"
        db: 0
        poolSize: 10
        maxRetries: 3
        prefix: "dev"

    rabbitmq:
      url: "amqp://user:password@turbo-mailer-rabbitmq:5672"

    log:
      level: debug

worker:
  replicaCount: 1

  image:
    repository: turbo-mailer-server
    pullPolicy: Always
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 5000

  resources: {}

  domains: []

  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values: [worker]
          topologyKey: kubernetes.io/hostname

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: password
  master:
    disableCommands: []
    persistence:
      enabled: true
      size: 5Gi
  replica:
    replicaCount: 0

rabbitmq:
  enabled: true
  auth:
    username: user
    password: password
  persistence:
    enabled: true
    size: 10Gi
  replicaCount: 1
  resources: {}

postgresql:
  enabled: true
  architecture: standalone
  auth:
    postgresPassword: password
    username: turbomailer
    password: password
    database: turbo-mailer
  primary:
    persistence:
      enabled: true
      size: 80Gi
    resources: {}
