sha: "34fe836f39623b0337c45ebec5f3a56f24360ea1"

frontend:
  replicaCount: 1

  image:
    repository: turbo-mailer-frontend
    pullPolicy: Always
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"
      nginx.ingress.kubernetes.io/server-snippet: |
        chunked_transfer_encoding on;
        proxy_ignore_headers 'X-Accel-Buffering';
        proxy_buffering off;
        proxy_request_buffering off;
    hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}

  pdb:
    enabled: true
    minAvailable: 1
    # maxUnavailable: 1

api:
  replicaCount: 1

  image:
    repository: turbo-mailer-server
    pullPolicy: Always
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 5000

  resources: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}

  config: |
    server:
      address: :5000

    database:
      turbo-mailer:
        uri: "postgres://turbomailer:password@turbo-mailer-postgresql:5432/turbo-mailer?sslmode=disable"

    redis:
      turbo-mailer:
        name: "turbo-mailer"
        addr: "turbo-mailer-redis-master:6379"
        password: "password"
        db: 0
        poolSize: 10
        maxRetries: 3
        prefix: "dev"

    rabbitmq:
      url: "amqp://user:password@turbo-mailer-rabbitmq:5672"

    log:
      level: debug

  pdb:
    enabled: true
    minAvailable: 1
    # maxUnavailable: 1

worker:
  replicaCount: 1

  image:
    repository: turbo-mailer-server
    pullPolicy: Always
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 5000

  resources: {}

  domains: []

  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values: [worker]
          topologyKey: kubernetes.io/hostname

dispatcher:
  replicaCount: 1

  image:
    repository: turbo-mailer-server
    pullPolicy: Always
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 5000

  resources: {}

  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values: [dispatcher]
          topologyKey: kubernetes.io/hostname

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: password
  master:
    disableCommands: []
    persistence:
      enabled: true
      size: 5Gi
  replica:
    replicaCount: 0

rabbitmq:
  enabled: true
  auth:
    username: user
    password: password
    erlangCookie: HTYGTwQJcAI4PwlbMd5RBkr3p5vpbolc
  persistence:
    enabled: true
    size: 10Gi
  replicaCount: 1
  resources: {}

postgresql:
  enabled: true
  architecture: standalone
  auth:
    postgresPassword: password
    username: turbomailer
    password: password
    database: turbo-mailer
  primary:
    persistence:
      enabled: true
      size: 80Gi
    resources: {}
