name: Deploy

on:
  push:
    branches:
      - master
      - develop
      - test
    tags:
      - "v[0-9]+.[0-9]+.[0-9]*"
    paths-ignore:
      - "**/*.md"
      - "charts/**"
      - "deploy/**"
      - "docs/**"
      - "helps/**"
      - "infra/**"
      - "install/**"
  workflow_dispatch:
    inputs:
      env_input:
        description: "Deployment environment"
        required: true
        type: choice
        default: test
        options:
          - test
          - dev
          - prod
      ref:
        description: "The particular branch or commit you wish to deploy"
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.event.inputs.env_input }}
  cancel-in-progress: true

env:
  ENVIRONMENT: |-
    ${{
      github.ref_type == 'tag' && 'prod' ||
      github.ref == 'refs/heads/master' && 'master' ||
      github.ref == 'refs/heads/develop' && 'dev' ||
      github.ref == 'refs/heads/test' && 'test' ||
      github.event.inputs.env_input || 'unknown'
    }}
  FRONTEND_REPO: ${{ secrets.DOCKER_USERNAME }}/turbo-mailer-frontend
  SERVER_REPO: ${{ secrets.DOCKER_USERNAME }}/turbo-mailer-server

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: green-dill/turbo-mailer/.github/actions/checkout@develop

      - name: Check for changes in charts directory
        id: check_charts
        run: |
          if git diff --name-only ${{ github.event.before }} HEAD | grep -q "^charts/"; then
            echo "charts_changed=true" >> $GITHUB_ENV
          else
            echo "charts_changed=false" >> $GITHUB_ENV
          fi

      - uses: helmfile/helmfile-action@v1.9.4
        if: env.charts_changed == 'true'
        with:
          helmfile-args: lint

  build:
    name: Build docker image | ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          # repo name can't use env expression, so we have to use hardcoded name
          - name: server
            context: ./turbo-mailer-server
            repo: turbo-mailer-server
          - name: frontend
            context: ./turbo-mailer-frontend
            repo: turbo-mailer-frontend
    steps:
      - uses: green-dill/turbo-mailer/.github/actions/checkout@develop

      - name: Setup | Use Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup | Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Images | ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.context }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          build-args: |
            COMMITID=${{ env.GIT_SHA }}
            ENVIRONMENT=${{ env.ENVIRONMENT }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.repo }}:${{ env.TARGET_REF }}
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.repo }}:latest

  update_manifest:
    name: Update manifest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: green-dill/turbo-mailer/.github/actions/checkout@develop

      - name: Setup | Install ruamel.yaml
        run: pip install ruamel.yaml

      - name: Manifest | Update
        shell: python
        run: |
          import os
          from ruamel.yaml import YAML

          env = os.environ['ENVIRONMENT']
          sha = os.environ['GITHUB_SHA']
          target_ref = os.environ['TARGET_REF']
          server_repo = os.environ['SERVER_REPO']
          frontend_repo = os.environ['FRONTEND_REPO']

          print(f"Environment: {env}")
          print(f"SHA: {sha}")
          print(f"Target Ref: {target_ref}")
          print(f"Server Repo: {server_repo}")
          print(f"Frontend Repo: {frontend_repo}")

          def update(file, updates):
              if not os.path.exists(file):
                  print(f"{file} not found")
                  return

              yaml = YAML()
              yaml.preserve_quotes = True
              with open(file, "r") as f:
                  data = yaml.load(f)

              def merge(source, destination):
                  for key, value in source.items():
                      if isinstance(value, dict):
                          node = destination.setdefault(key, {})
                          merge(value, node)
                      else:
                          destination[key] = value
                  return destination

              merge(updates, data)

              with open(file, "w") as f:
                  yaml.dump(data, f)

          # Update charts/turbo-mailer/values.yaml
          update("charts/turbo-mailer/values.yaml", {
              "sha": sha
          })

          # Update deploy/values-*.yaml
          if env in ["dev", "develop"]:
              deploy_file = "deploy/values-dev.yaml"
              postfix_deploy_file = "deploy/values-postfix-dev.yaml"
          elif env in ["test", "staging"]:
              deploy_file = "deploy/values-test.yaml"
              postfix_deploy_file = "deploy/values-postfix-test.yaml"
          elif env in ["prod", "production", "master"]:
              deploy_file = "deploy/values-prod.yaml"
              postfix_deploy_file = "deploy/values-postfix-prod.yaml"
          else:
              raise ValueError(f"Unsupported environment: {env}")

          update(deploy_file, {
              "frontend": {
                  "image": {
                      "repository": f"{frontend_repo}",
                      "tag": target_ref
                  }
              },
              "api": {
                  "image": {
                      "repository": f"{server_repo}",
                      "tag": target_ref
                  }
              },
              "worker": {
                  "image": {
                      "repository": f"{server_repo}",
                      "tag": target_ref
                  }
              }
          })

          update(postfix_deploy_file, {
              "setupDNS": {
                  "image": {
                      "repository": f"{server_repo}",
                      "tag": target_ref
                  }
              }
          })

      - name: Manifest | Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ -n $(git status -s) ]]; then
            commit_args=(
              -a
              -m "chore(ci): ${{ github.ref_name }} $(expr substr '${{ github.sha }}' 1 7)"
              -m "update manifest for deployment, ${{ github.repository }} build:${{ github.run_number }}"
            )
            if [[ "${{ github.event_name }}" == 'push' ]]; then
              commit_args+=(
                -m "Co-authored-by: ${{ github.event.pusher.name }} <${{ github.event.pusher.email }}>"
              )
            fi
            git commit "${commit_args[@]}"
            git pull --rebase
            git push
          fi

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: update_manifest
    steps:
      - name: Set deployment condition
        run: |
          if [[ "${{ github.event.inputs.env_input }}" =~ ^(dev|test|prod)$ ]] || \
             [[ "${{ github.ref }}" =~ ^refs/heads/(develop|test)$ ]] || \
             [[ "${{ github.ref_type }}" == "tag" ]]; then
            if [[ "${{ env.ENVIRONMENT }}" == "prod" && -z "${{ secrets.KUBECONFIG_PROD }}" ]] || \
               [[ "${{ env.ENVIRONMENT }}" == "dev" && -z "${{ secrets.KUBECONFIG_DEV }}" ]] || \
               [[ "${{ env.ENVIRONMENT }}" == "test" && -z "${{ secrets.KUBECONFIG_TEST }}" ]]; then
              echo "SHOULD_DEPLOY=false" >> $GITHUB_ENV
              echo "Deployment skipped: KUBECONFIG is not set"
            else
              echo "SHOULD_DEPLOY=true" >> $GITHUB_ENV
            fi
          else
            echo "SHOULD_DEPLOY=false" >> $GITHUB_ENV
            echo "Deployment skipped: Environment condition not met"
          fi
      - uses: green-dill/turbo-mailer/.github/actions/checkout@develop
        if: env.SHOULD_DEPLOY == 'true'

      - name: KUBECONFIG | Setup
        if: env.SHOULD_DEPLOY == 'true'
        run: |
          mkdir -p $HOME/.kube
          if [[ "${{ env.ENVIRONMENT }}" == "prod" ]]; then
            echo "${{ secrets.KUBECONFIG_PROD }}" > $HOME/.kube/config
          elif [[ "${{ env.ENVIRONMENT }}" == "dev" ]]; then
            echo "${{ secrets.KUBECONFIG_DEV }}" > $HOME/.kube/config
          elif [[ "${{ env.ENVIRONMENT }}" == "test" ]]; then
            echo "${{ secrets.KUBECONFIG_TEST }}" > $HOME/.kube/config
          else
            echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          fi
          chmod 600 $HOME/.kube/config

      - name: Helmfile | Diff
        uses: helmfile/helmfile-action@v1.9.4
        if: env.SHOULD_DEPLOY == 'true'
        with:
          helmfile-args: --environment ${{ env.ENVIRONMENT }} diff

      - name: Helmfile | Apply
        uses: helmfile/helmfile-action@v1.9.4
        if: env.SHOULD_DEPLOY == 'true'
        with:
          helmfile-args: --environment ${{ env.ENVIRONMENT }} apply
